name: Unit Tests

on:
  push:
    branches:
      - "main"
    pull_request:
      branches:
        - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
        working-directory: client/

      - name: Lint with ESLint
        run: npm run lint
        working-directory: client/

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version:
            ${{ matrix.node-version }}
            # we need to make a Node.js server first :p
      # - name: Setup Node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #
      # - name: Install Dependencies
      #   run: npm ci
      #   working-directory: server/
      #
      # - name: Run tests
      #   run: npm test
      #   working-directory: server/
